- name: Setup ControlNode and Configure Targets
  hosts: localhost
  become: yes
  vars:
    control_node_ip: "{{ control_node_ip }}"
    target_ips: "{{ target_ips }}"
    ssh_key_dir: "/tmp/ssh_keys"


  tasks:
    - name: Debug target_ips
      debug:
        var: target_ips

    - name: Update package manager
      apt:
        update_cache: yes

    - name: Install required packages
      apt: 
        name:
          - sshpass
          - git
        state: present

    - name: Add control node to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ control_node_ip }} controlnode"

    - name: Add target nodes to inventory
      copy:
        dest: /etc/ansible/hosts
        content: |
          [targets]
          {% for ip in target_ips %}
          {{ ip }} ansible_ssh_private_key_file=.ssh/node0{{ loop.index0 }}/id_rsa
          {% endfor %}

    - name: Ensure SSH key directory exists
      file:
        path: "{{ ssh_key_dir }}"
        state: directory
        mode: '0755'

    - name: Generate SSH key for each target
      command: ssh-keygen -t rsa -b 2048 -f "{{ ssh_key_dir }}/id_rsa_{{ item }}" -q -N ""
      loop: "{{ target_ips }}"
      loop_control:
        label: "{{ item }}"
      args:
        creates: "{{ ssh_key_dir }}/id_rsa_{{ item }}"

    - name: Distribute public key to target nodes
      copy:
        src: "{{ ssh_key_dir }}/id_rsa_{{ item }}.pub"
        dest: "/home/vagrant/.ssh/authorized_keys"
        owner: vagrant
        group: vagrant
        mode: '0600'
      loop: "{{ target_ips }}"
      delegate_to: "{{ item }}"


    - name: Add jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        state: present

    - name: Add jenkins repository
      apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present

    - name: Update package update_cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service
      systemd: 
        name: jenkins
        state: started
        enabled: yes