---
- name: Install wget
  apt:
    name: wget
    state: present

- name: Download .NET SDK
  get_url:
    url: "https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb"
    dest: "/tmp/packages-microsoft-prod.deb"

- name: Install .NET SDK .deb package
  apt:
    deb: "/tmp/packages-microsoft-prod.deb"
    state: present

- name: Add Microsoft package repository
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Update apt sources for .NET SDK
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/ubuntu/20.04/prod focal main"
    state: present
  notify:
    - Update apt cache

- name: Install .NET SDK
  apt:
    name: dotnet-sdk-9.0
    state: present

- name: Install ASP.NET Core Runtime
  apt:
    name: aspnetcore-runtime-9.0
    state: present
